# Git Secrets Guard Configuration File
# Place this file in your repository root as .gitsecrets.yml

# Version of the configuration format
version: 1

# Enable/Disable the hook entirely
enabled: true

# Detection settings
detection:
  # Enable/Disable specific detection categories
  api_keys: true
  passwords: true
  private_keys: true
  personal_info: true
  high_entropy: true
  
  # Detection sensitivity (low, medium, high)
  sensitivity: medium

# Custom patterns to detect (regex)
custom_patterns:
  # - pattern: "CUSTOM_SECRET_[A-Z0-9]{32}"
  #   description: "Custom secret pattern"
  #   severity: high  # low, medium, high
  
# Custom keywords to detect (case-insensitive)
custom_keywords:
  # - "MY_CUSTOM_SECRET"
  # - "INTERNAL_API_KEY"

# Whitelist settings
whitelist:
  # Files to skip checking entirely
  files:
    # - "test/fixtures/fake-secrets.txt"
    # - "docs/examples/*"
    
  # Patterns to ignore (regex)
  patterns:
    # - "sk-test[a-zA-Z0-9]{32}"  # Test API keys
    # - "example\\.com"  # Example domains
    
  # Specific strings to ignore
  strings:
    # - "sk-1234567890abcdef1234567890abcdef"  # Documentation example
    
  # File extensions to skip
  extensions:
    # - ".md"  # Skip markdown files
    # - ".txt"  # Skip text files
    
  # Directories to skip (relative to repo root)
  directories:
    # - "node_modules"
    # - "vendor"
    # - ".git"

# Reporting settings
reporting:
  # Show detected pattern in output
  show_pattern: true
  # Show line number where secret was found
  show_line_number: false
  # Show context around the detection
  show_context: false
  # Maximum number of issues to show per file
  max_issues_per_file: 10

# Actions when secrets are detected
actions:
  # Block the commit (true) or just warn (false)
  block_commit: true
  # Create a log file of detections
  create_log: false
  # Log file path (relative to repo root)
  log_path: ".gitsecrets.log"

# Override settings for specific environments
environments:
  # Example: CI/CD environment
  ci:
    enabled: true
    actions:
      block_commit: true
      create_log: true
  
  # Example: Development environment
  development:
    detection:
      sensitivity: low
    actions:
      block_commit: false
