# Example Git Secrets Guard Configuration
# Copy this file to .gitsecrets.yml in your repository root and customize

version: 1
enabled: true

detection:
  api_keys: true
  passwords: true
  sensitivity: medium

# Example: Custom patterns for your organization
custom_patterns:
  - pattern: "INTERNAL_KEY_[A-Z0-9]{32}"
    description: "Internal API key format"
    severity: high
  - pattern: "STAGING_TOKEN_[a-z0-9]{16}"
    description: "Staging environment tokens"
    severity: medium

# Example: Custom keywords specific to your project
custom_keywords:
  - "COMPANY_SECRET"
  - "INTERNAL_API_KEY"
  - "PRIVATE_ENDPOINT"

# Example: Whitelist configuration
whitelist:
  # Skip checking these files entirely
  files:
    - "README.md"
    - "README.zh-CN.md"
    - "docs/examples/sample-config.yml"
    - "test/fixtures/*.txt"
    
  # Ignore these specific patterns (useful for test keys)
  patterns:
    - "sk-test[a-zA-Z0-9]{32}"  # Test API keys
    - "example\\.com"            # Example domains
    - "localhost:[0-9]{4}"       # Local development URLs
    - "sk-1234567890abcdef"     # Documentation examples
    
  # Ignore these exact strings
  strings:
    - "sk-1234567890abcdef1234567890abcdef"  # Documentation example
    - "password123"                           # Example password in docs
    - "test-api-key-do-not-use"              # Test key
    
  # Skip files with these extensions
  extensions:
    - ".md"      # Markdown documentation
    - ".txt"     # Text files
    - ".example" # Example files
    
  # Skip these directories
  directories:
    - "node_modules"
    - "vendor"
    - ".git"
    - "test/fixtures"
    - "docs/examples"

reporting:
  show_pattern: true
  max_issues_per_file: 5

actions:
  block_commit: true  # Set to false for warning-only mode
  create_log: false
